# Generated by Django 2.2.5 on 2019-09-23 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcp_registro_op', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroop',
            name='prev_entrega',
        ),
    ]
