# Generated by Django 2.2.5 on 2019-09-22 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pcp_registro_op', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEntrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produzido', models.DateField(blank=True, null=True)),
                ('obs', models.CharField(blank=True, max_length=50, null=True)),
                ('entrega', models.DateField(blank=True, null=True)),
                ('cancelada', models.BooleanField(default=False)),
                ('op', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='pcp_registro_op.RegistroOp')),
            ],
        ),
    ]
